bladestan/bladestan

src/Compiler/BladeToPHPCompiler.php

Remove duplicate param tag

---

README.md

Fix contributors link in README

---

README.md

I do not understand the original sentence, what the two things are: ... and ... 😵 
Please do it without me.

Describe Bladestan

---

README.md

From #38 
Hope that's alright :)

Update README.md: phpstan extension installer or config includes

---

tests/Rules/BladeRuleTest.php
tests/Rules/Fixture/laravel-view-function.php

Related to #33, this is a test for the case that works correctly so can be merged as is.

Test passing variables via compact()

---

src/NodeAnalyzer/BladeViewMethodsMatcher.php
src/NodeAnalyzer/LaravelViewFunctionMatcher.php
tests/Rules/BladeRuleTest.php
tests/Rules/Fixture/laravel-component-function.php
tests/Rules/Fixture/laravel-component-method.php
tests/Rules/templates/component.blade.php

Add basic support for components

---

src/NodeAnalyzer/BladeViewMethodsMatcher.php
src/TemplateCompiler/ErrorFilter.php
tests/Rules/BladeRuleTest.php
tests/Rules/Fixture/laravel-mailable-method.php
tests/TemplateCompiler/ErrorFilterTest.php

No functional changes just cruft that was left behind with other of my PRs

Clean up error filtering and tests

---

src/Compiler/BladeToPHPCompiler.php

See https://github.com/TomasVotruba/bladestan/issues/71
---
Closes #71 (Edit by @TomasVotruba to autoclose on merge)

Add more flexibility on spacing

---

src/NodeAnalyzer/BladeViewMethodsMatcher.php
tests/Rules/BladeRuleTest.php
tests/Rules/Fixture/laravel-mail_message-method.php

Add support for MailMessage::view()

---

composer.json
ecs.php
phpstan.neon
rector.php
src/NodeAnalyzer/BladeViewMethodsMatcher.php
src/NodeAnalyzer/LaravelViewFunctionMatcher.php
src/PhpParser/NodeVisitor/BladeLineNumberNodeVisitor.php
src/Rules/BladeRule.php
src/TemplateCompiler/Reflection/PrivatesAccessor.php
src/ValueObject/CompiledTemplate.php
src/ViewRuleHelper.php
tests/Blade/PhpLineToTemplateLineResolverTest.php
tests/Rules/BladeRuleTest.php

Laravel 11 is behind doors, time to test this package in the wild :)

Drop Laravel 8, allow Laravel 11

---

src/ErrorReporting/PHPStan/ErrorFormatter/BladeTemplateErrorFormatter.php

I would be happy if `BladeTemplateErrorFormatter` would display error tip like PHPStan's `TableErrorFormatter`.

Display error tip

---

config/extension.neon
src/NodeAnalyzer/LaravelContentMatcher.php
src/NodeAnalyzer/LaravelViewFunctionMatcher.php
src/NodeAnalyzer/MagicViewWithCallParameterResolver.php
src/NodeAnalyzer/MailablesContentMatcher.php
src/Rules/BladeRule.php
src/ViewRuleHelper.php
tests/Rules/BladeRuleTest.php
tests/Rules/Fixture/laravel-mailable-method.php

Support Mailable content()

---

src/NodeAnalyzer/ViewVariableAnalyzer.php
src/PhpParser/NodeVisitor/ViewFunctionArgumentsNodeVisitor.php

Handle dynamic method calls

---

src/Compiler/BladeToPHPCompiler.php
tests/Compiler/BladeToPHPCompiler/Fixture/backed-component.blade.php
tests/Compiler/BladeToPHPCompiler/Fixture/basic_echo.blade.php
tests/Compiler/BladeToPHPCompiler/Fixture/basic_echo_with_multiple_lines.blade.php
tests/Compiler/BladeToPHPCompiler/Fixture/basic_include.blade.php
tests/Compiler/BladeToPHPCompiler/Fixture/bubble_up_use_statments.php
tests/Compiler/BladeToPHPCompiler/Fixture/component_include.blade.php
tests/Compiler/BladeToPHPCompiler/Fixture/dynamic-component.php
tests/Compiler/BladeToPHPCompiler/Fixture/implicit_terminated_statments.php
tests/Compiler/BladeToPHPCompiler/Fixture/livewire_include.blade.php
tests/Compiler/BladeToPHPCompiler/Fixture/multiline_echo_with_html.blade.php
tests/Compiler/BladeToPHPCompiler/Fixture/multiple_include.blade.php
tests/Compiler/BladeToPHPCompiler/Fixture/nested_if_and_foreach.blade.php
tests/Compiler/BladeToPHPCompiler/Fixture/sections_are_removed.php

This solves various issues with methods that are called on it by blade directives like `@once`

Add $__env to known variables (support `@once`)

---

src/Compiler/BladeToPHPCompiler.php
src/PhpParser/NodeVisitor/TransformEach.php
tests/Compiler/BladeToPHPCompiler/Fixture/dynamic-component.php
tests/Compiler/BladeToPHPCompiler/Fixture/each.php

Implement @each

---

composer.json
config/template-compiler/services.neon
src/Compiler/BladeToPHPCompiler.php
src/Compiler/LivewireTagCompiler.php
src/Laravel/View/BladeCompilerFactory.php
src/NodeAnalyzer/BladeViewMethodsMatcher.php
src/NodeAnalyzer/LaravelViewFunctionMatcher.php
src/ValueObject/AbstractInlinedElement.php
tests/Compiler/BladeToPHPCompiler/BladeToPHPCompilerTest.php

Use application's BladeCompiler

---

src/NodeAnalyzer/ViewVariableAnalyzer.php
tests/Rules/BladeRuleTest.php
tests/Rules/Fixture/data-from-variable.php

If data is given via a variable the view is unable to see the data.

Test we get data from variables

---

src/NodeAnalyzer/MagicViewWithCallParameterResolver.php
src/NodeAnalyzer/MailablesContentMatcher.php
src/PhpParser/NodeVisitor/ViewFunctionArgumentsNodeVisitor.php
tests/Rules/BladeRuleTest.php
tests/Rules/Fixture/laravel-mailable-method.php

Add testcase for Illuminate\Mail\Mailable::view()->with()

---

composer.json

Add Laravel 12 support

---

src/Compiler/BladeToPHPCompiler.php
src/PhpParser/NodeVisitor/IncludeCollector.php
tests/Rules/BladeRuleTest.php
tests/Rules/Fixture/laravel-include-value-from-array.php
tests/skeleton/resources/views/value-from-array.blade.php

Use PhpParser rather then preg to find includes
